# Generated by Django 4.0.3 on 2022-04-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateField(null=True, verbose_name='Data da Publicação'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=120, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
    ]
